apiVersion: v1
kind: Service
metadata:
  name: amandava-hello-python-service
spec:
  selector:
    app: amandava-hello-python
  ports:
  - protocol: "TCP"
    port: 5001
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amandava-hello-python
spec:
  selector:
    matchLabels:
      app: amandava-hello-python
  replicas: 2
  template:
    metadata:
      labels:
        app: amandava-hello-python
    spec:
      containers:
      - name: amandava-hello-python
        image: amandava_hello_python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000